spring:
  session:
    timeout: 1m

server:
  port: 8081
  servlet:
    context-path: /api
    session:
      timeout: 1m
      cookie:
        http-only: true
        secure: true
        max-age: 1m
      tracking-modes:
        - COOKIE