spring:
  session:
    timeout: 1m
    jdbc:
      table-name: SESSION
  data:
    mongodb:
      ##Change this to the Mongo Connection URI
      uri: mongodb://localhost/test

server:
  port: 8081
  servlet:
    context-path: /app
    session:
      timeout: 1m
      cookie:
        http-only: true
        secure: true
        max-age: 1m
      tracking-modes:
        - COOKIE